"""Codex harness delivery (`.codex/config.toml` + `.codex/hooks.json`).

Codex surfaces (CLI, IDE extension, desktop) share MCP configuration; lifecycle
hooks run from the session cwd with per-hash trust review via ``/hooks``.

Spec (developers.openai.com/codex/{mcp,config-basic,hooks}, guides/agents-md):

* Config: ``~/.codex/config.toml`` (user) + ``<repo>/.codex/config.toml``
  (project, trusted-only). Precedence CLI > project > profile > user.
  MCP shape: ``[mcp_servers.evidencespine] command="..." args=[...]``.
* Hooks: ``hooks.json`` OR inline ``[hooks]``/``[[hooks.Event]]`` in
  ``config.toml``; locations ``~/.codex/`` + ``<repo>/.codex/`` (additive).
  Events include SessionStart/SessionEnd/PreToolUse/PostToolUse/
  PreCompact/PostCompact/UserPromptSubmit/Stop/SubagentStart/Stop.
* Stdout: SessionStart/UserPromptSubmit plaintext is added as context;
  all other events (notably PreCompact) MUST return
  ``{"hookSpecificOutput": {"hookEventName": ..., "additionalContext": ...}}``.
* Timeouts: default 600s; SessionEnd/Interrupt 1s default, 3s max.
* Features: ``[features] hooks=true`` (stable; ``codex_hooks`` deprecated).
* AGENTS.md: global ``~/.codex/AGENTS.md`` first, then git-root -> cwd,
  cumulative ``project_doc_max_bytes`` = 32KiB.
* MCP ``instructions`` is read on init; keep first 512 chars self-contained.

Every hook fails open (never breaks the session).
"""

from __future__ import annotations

import json
import shlex
from typing import Any, Dict, Optional


def hook_command(
    executable: str,
    action: str,
    *,
    base_dir: Optional[str] = None,
) -> str:
    """Build a shell-safe hook command for Codex hooks.json."""
    parts = shlex.split(executable) if executable else ["evidencespine"]
    parts += ["harness", "codex", action]
    if base_dir:
        parts += ["--base-dir", base_dir]
    return shlex.join(parts)


def mcp_server_table(executable: str, base_dir: str) -> Dict[str, Any]:
    """Return the ``[mcp_servers.evidencespine]`` table body."""
    argv = shlex.split(executable) if executable else ["evidencespine"]
    command = argv[0]
    args = [*argv[1:], "mcp", "--base-dir", base_dir]
    return {"command": command, "args": args}


def render_config_toml(executable: str = "evidencespine", base_dir: str = ".evidencespine") -> str:
    """Render a minimal ``.codex/config.toml`` snippet (MCP + features)."""
    table = mcp_server_table(executable, base_dir)
    lines = [
        "# EvidenceSpine — Codex harness (generated by `evidencespine harness install --harness codex`)",
        "# Project layer: <repo>/.codex/config.toml (requires trusted project).",
        "# Global layer: ~/.codex/config.toml (same shape).",
        "",
        "[features]",
        "hooks = true",
        "",
        "[mcp_servers.evidencespine]",
        f"command = {json.dumps(table['command'], ensure_ascii=True)}",
        f"args = {json.dumps(table['args'], ensure_ascii=True)}",
        "",
    ]
    return "\n".join(lines)


def build_hooks_json(
    *,
    executable: str = "evidencespine",
    base_dir: Optional[str] = None,
) -> Dict[str, Any]:
    """Build ``.codex/hooks.json`` wiring SessionStart/SessionEnd/PreCompact.

    SessionStart uses plaintext stdout (added as developer context).
    SessionEnd is advisory (1s default timeout). PreCompact MUST use the
    JSON envelope or stdout is ignored.
    """

    def _entry(action: str, timeout: int) -> Dict[str, Any]:
        return {
            "matcher": "",
            "hooks": [
                {
                    "type": "command",
                    "command": hook_command(executable, action, base_dir=base_dir),
                    "timeout": timeout,
                }
            ],
        }

    return {
        "hooks": {
            "SessionStart": [_entry("session-start", 30)],
            "SessionEnd": [_entry("session-stop", 3)],
            "PreCompact": [_entry("precompact", 30)],
        }
    }


def precompact_envelope(note: str) -> str:
    """Wrap a retain-through-compaction note in the Codex PreCompact envelope."""
    return json.dumps(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreCompact",
                "additionalContext": str(note or ""),
            }
        },
        ensure_ascii=True,
    )
